### ISSUE TITLE
Updates for latest libav?

### ISSUE THREAD

**Issue by bokken** [operutka/jlibav#1]
Are updates planned to this project to support the 10.x and/or 11.x releases of libav?

**Comment by operutka** [comment]
Shortly - Yes, they are. :D 

I've been a bit busy lately so I haven't had much time for this project. There's also a problem with libav 10.x which causes segfaults in case multiple threads are used for encoding. I've been unable to solve it so far (any help is welcome). I'll try to finally resolve the issue once I find some spare time.

**Comment by bokken** [comment]
Has trunk been updated for the non-passive changes documented in 10[1]?

> One of the main features of this release is the addition of reference-counted
> data buffers to Libav and their use in various structures. Specifically, the
> data buffers used by AVPacket and AVFrame can now be reference counted, which
> should allow to significantly simplify many use cases. In addition,
> reference-counted AVFrames can now be used in libavfilter, avoiding the need
> for a separate libavfilter-specific frame structure. Frames can now be passed
> straight from the decoders into filters or from filters to encoders.
> 
> These additions made it necessary to bump the major versions of libavcodec,
> libavformat, libavdevice, libavfilter, and libavutil, which was accompanied by
> dropping some old deprecated APIs. These libraries are thus not ABI- or API-
> compatible with the previous release. All the other libraries (libavresample
> and libswscale) should be both ABI- and API-compatible.

Your comment also sounds somewhat similar to something being described in the version 11 release notes[2]:

> When using libavcodec for decoding or encoding and libavformat for demuxing or muxing,
> the standard practice was to use the stream codec context (AVStream.codec) for
> actual decoding or encoding. There are multiple problems with this pattern
> (the main one is that the decoder/demuxer or encoder/muxer are not necessarily
> synchronized and may overwrite each other's state), so it is now strongly
> discouraged and will likely be deprecated in the future.

[1] - https://libav.org/releases/libav-10.5.release
[2] - https://libav.org/releases/libav-11.release

**Comment by operutka** [comment]
> Has trunk been updated for the non-passive changes documented in 10[1]?

Yes, I believe so. Check these:
[FrameWrapper55](https://github.com/operutka/jlibav/blob/master/jlibav/src/main/java/org/libav/avcodec/FrameWrapper55.java)
[PacketWrapper55](https://github.com/operutka/jlibav/blob/master/jlibav/src/main/java/org/libav/avcodec/PacketWrapper55.java)
[AVFrame55](https://github.com/operutka/jlibav/blob/master/jlibav/src/main/java/org/libav/avcodec/bridge/AVFrame55.java)
[AVPacket55](https://github.com/operutka/jlibav/blob/master/jlibav/src/main/java/org/libav/avcodec/bridge/AVPacket55.java)

> Your comment also sounds somewhat similar to something being described in the version 11 release notes[2]

Thanks, I'll take a look at it.
